spring:
  cloud:
    stream:
      bindings:
        output:
          destination: source #can be anything.
          producer:
            requiredGroups: source.output #can by anything.
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost:5672