spring:
  cloud:
    stream:
      bindings:
        input:
          destination: source #can by anything, but must match producer's definition.
          group: source.output #can by anything, but must match producer's definition.
        output:
          destination: processor #can by anything.
          producer:
            requiredGroups: processor.output #can by anything.
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost:5672