spring:
  cloud:
    stream:
      bindings:
        input:
          destination: processor #can by anything, but must match producer's definition.
          group: processor.output #can by anything, but must match producer's definition.
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost:5672