spring:
  cloud:
    stream:
      bindings:
        input:
          destination: processor
          group: processor.output
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost:5672